services:
  - type: web
    name: gcbc-game
    env: static
    buildCommand: 'echo "window.ENV = { SUPABASE_URL: \"$SUPABASE_URL\", SUPABASE_KEY: \"$SUPABASE_KEY\" };" > env.js'
    staticPublishPath: ./
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
