services:
  - type: web
    name: gcbc-game
    env: static
    buildCommand: 'sed -i "s/YOUR_GOOGLE_CLIENT_ID_HERE/$GOOGLE_CLIENT_ID/g" index.html'
    staticPublishPath: ./
    envVars:
      - key: GOOGLE_CLIENT_ID
        sync: false
